name: 'Static code analysis'

on:
    push:
    workflow_dispatch:

jobs:
    analyze:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Download script
              run: |
                curl --silent --output /usr/local/bin/static-code-analysis.sh \
                    https://gitlab.com/madebyTimo/scripts-development/-/raw/main/scripts/static-code-analysis.sh && \
                    chmod +x /usr/local/bin/static-code-analysis.sh
            - name: Analyze
              run: static-code-analysis.sh
            - name: Publish result
              if: success() || failure()
              run: cat test-results/*.txt >> $GITHUB_STEP_SUMMARY
